apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-base-values
  namespace: flux-system
data:
  values.yaml: |
    uaDeployment:
      image:
        repository: stonebranch/universal-agent
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      storageRequest: 1Gi
      storageClassName: "default"
      accessMode: ReadWriteOnce
      pvc:
        enabled: true
    istio:
      enabled: true
      TLSProtocol: "TLSV1_2"
      udmConnectionPort: 446
      udmConnectionPortInternal: 15446
    workloadIdentity:
      enabled: false
    uaConfig:
      uagAutostart: "yes"
      omsAutostart: "no"
      uemAutostart: "no"
