apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ua-dev-k8s
  namespace: sb-ua-dev-k8s
spec:
  interval: 10m
  chart:
    spec:
      chart: helm-repo/helm/helm_ua_v1.5.1-aks
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    uaDeployment:
      image:
        repository: stonebranch/universal-agent
        tag: "7.9.0.0"
      replicas: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      storageRequest: 1Gi
      storageClassName: "default"
      accessMode: ReadWriteOnce
      pvc:
        enabled: true
    uaConfig:
      netname: "UA-DEV-K8S"
      omsServers: "7878@ps1.stonebranchdev.cloud"
      uagAutostart: "yes"
      omsAutostart: "no"
      uemAutostart: "no"
      otelenabletracing: "yes"
      otelexportmetrics: "yes"
      oteltraceendpoint: "http://alloy.dev.svc.cluster.local:4318"
      otelmetricsendpoint: "http://alloy.dev.svc.cluster.local:4318"
      otelservicename: "ua-dev-k8s"
    workloadIdentity:
      enabled: true
      clientId: "e0ad4b70-59ef-474b-832c-77ecc99d6c6f"
      serviceAccountName: "ua-dev-k8s-sa"
    istio:
      enabled: true
      host: "ua-dev-k8s.stonebranchdev.cloud"
      TLSProtocol: "TLSV1_2"
      udmConnectionPort: 446
      udmConnectionPortInternal: 15446
